version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    entrypoint:
      - /usr/src/app/entrypoint.sh
      - /usr/src/app/entrypoint.worker.sh
      - /usr/src/app/entrypoint.daphne.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  redis:
    restart: always
    image: redis
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redisdata:
