version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-static:/usr/src/web_app/static
    env_file: .env.prod
    command: /usr/local/bin/gunicorn web_app.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: postgresql/.env.prod

  redis:
    restart: always
    image: redis
    ports:
      - "6379"
    volumes:
      - redisdata:/data

volumes:
  web-static:
  pgdata:
  redisdata:
