version: '3.8'

services:
  web:
    #restart: always
    build: ./web
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint:
      - /usr/src/app/entrypoint.sh
      - /usr/src/app/entrypoint.worker.sh
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db
      - rabbitmq
      - celery

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 8001:5555
    env_file:
      - ./.env.flower.dev

  celery:
    #restart: always
    build: ./web
    container_name: celery
    command: celery -A app worker -l INFO --concurrency 3 -E -Q DiscoveryQueue,ScannerQueue,Queue
    volumes:
      - ./web/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - db
      - rabbitmq

  db:
    image: postgres
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.db.dev

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 8002:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  redisdata:
  rabbitmqdata:
