version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    entrypoint:
      - /usr/src/app/entrypoint.prod.sh
      - /usr/src/app/entrypoint.daphne.sh
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build:
      context: ./deploy
      dockerfile: nginx/Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80
    depends_on:
      - web

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - 8001:5555
    env_file:
      - ./.env.flower.dev

  celery_worker:
    #restart: always
    build: ./web
    container_name: celery_worker
    command: celery -A app worker -l INFO --concurrency 3 -E -Q DiscoveryQueue,ScannerQueue,Queue
    volumes:
      - ./web/:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db
      - rabbitmq

  celery_beat:
    #restart: always
    build: ./web
    container_name: celery_beat
    command: celery -A app beat -l INFO --concurrency 3 -E -S django -Q DiscoveryQueue,ScannerQueue,Queue
    volumes:
      - ./web/:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db
      - rabbitmq

  db:
    image: postgres
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.db.prod

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 8002:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

volumes:
  redisdata:
  rabbitmqdata:
  static_volume:
  media_volume:
  postgres_data:

