FROM nginx/nginx-unprivileged:1-alpine

LABEL maintainer="Mohammad Mehdi Abbaspour <mm.abbaspour@gmail.com>"

RUN apt-get update

RUN apt-get install python3 python3-pip postgresql-dev gcc python3-dev musl-dev

RUN pip3 install virtualenv

RUN mkdir /logs
RUN touch /logs/error.log /logs/access.log
RUN chmod -R 777 /logs
