# Generated by Django 4.2.1 on 2023-05-27 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discovery",
            name="created_by",
        ),
    ]
