# Generated by Django 4.2.1 on 2023-05-30 17:00

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0002_remove_discovery_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        default="0.0.0.0", verbose_name="IP Address"
                    ),
                ),
                (
                    "netmask",
                    models.GenericIPAddressField(
                        default="255.255.255.255", verbose_name="Netmask"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0, editable=False, verbose_name="Progress"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Ended at",
                    ),
                ),
                (
                    "graph",
                    models.JSONField(
                        blank=True, editable=False, null=True, verbose_name="Graph"
                    ),
                ),
                (
                    "tcp_ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, default=0),
                        default=[
                            80,
                            23,
                            443,
                            21,
                            22,
                            25,
                            3389,
                            110,
                            445,
                            139,
                            143,
                            53,
                            135,
                            3306,
                            8080,
                            1723,
                            111,
                            995,
                            993,
                            5900,
                            5432,
                            1433,
                            4022,
                            135,
                            1434,
                        ],
                        size=None,
                        verbose_name="TCP Ports",
                    ),
                ),
                (
                    "udp_ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, default=0),
                        default=[
                            631,
                            161,
                            137,
                            123,
                            138,
                            445,
                            135,
                            67,
                            53,
                            139,
                            500,
                            68,
                            520,
                            1900,
                            4500,
                            514,
                            49152,
                            162,
                            69,
                            1434,
                        ],
                        size=None,
                        verbose_name="UDP Ports",
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
                "abstract": False,
            },
        ),
    ]
