# Generated by Django 4.2.1 on 2023-05-30 17:22

import discovery.domain.popular_ports
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0003_scanner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanner",
            name="tcp_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, default=0),
                default=discovery.domain.popular_ports.popular_tcp_ports,
                size=None,
                verbose_name="TCP Ports",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="udp_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, default=0),
                default=discovery.domain.popular_ports.popular_udp_ports,
                size=None,
                verbose_name="UDP Ports",
            ),
        ),
    ]
