# Generated by Django 4.2.1 on 2023-07-28 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0006_discovery_created_by_scanner_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanner",
            name="tcp_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, default=0),
                default=[
                    80,
                    23,
                    443,
                    21,
                    22,
                    25,
                    3389,
                    110,
                    445,
                    139,
                    143,
                    53,
                    135,
                    3306,
                    8080,
                    1723,
                    111,
                    995,
                    993,
                    5900,
                    5432,
                    1433,
                    4022,
                    135,
                    1434,
                ],
                size=None,
                verbose_name="TCP Ports",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="udp_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, default=0),
                default=[
                    631,
                    161,
                    137,
                    123,
                    138,
                    445,
                    135,
                    67,
                    53,
                    139,
                    500,
                    68,
                    520,
                    1900,
                    4500,
                    514,
                    49152,
                    162,
                    69,
                    1434,
                ],
                size=None,
                verbose_name="UDP Ports",
            ),
        ),
    ]
