# Generated by Django 4.2.1 on 2023-08-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("discovery", "0007_alter_scanner_tcp_ports_alter_scanner_udp_ports"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovery",
            name="crontab",
            field=models.ForeignKey(
                blank=True,
                help_text="Crontab Schedule to run the task on.  Set only one schedule type, leave the others null.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.crontabschedule",
                verbose_name="Crontab Schedule",
            ),
        ),
        migrations.AddField(
            model_name="scanner",
            name="crontab",
            field=models.ForeignKey(
                blank=True,
                help_text="Crontab Schedule to run the task on.  Set only one schedule type, leave the others null.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.crontabschedule",
                verbose_name="Crontab Schedule",
            ),
        ),
    ]
