# Generated by Django 4.2.1 on 2023-08-17 06:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0008_discovery_crontab_scanner_crontab"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discovery",
            name="graph",
        ),
        migrations.RemoveField(
            model_name="scanner",
            name="graph",
        ),
        migrations.AddField(
            model_name="discovery",
            name="edges",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True, default="", editable=False, null=True
                    ),
                    default=[],
                    size=2,
                ),
                default=[],
                size=None,
                verbose_name="Edges",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discovery",
            name="nodes",
            field=models.JSONField(
                blank=True, default={}, editable=False, null=True, verbose_name="Nodes"
            ),
        ),
        migrations.AddField(
            model_name="scanner",
            name="edges",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True, default="", editable=False, null=True
                    ),
                    size=2,
                    default=[],
                ),
                default=[],
                size=None,
                verbose_name="Edges",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scanner",
            name="nodes",
            field=models.JSONField(
                blank=True, default={}, editable=False, null=True, verbose_name="Nodes"
            ),
        ),
    ]
