# Generated by Django 4.2.4 on 2023-08-18 21:54

import discovery.domain.popular_ports
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discovery", "0010_alter_discovery_edges_alter_scanner_edges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discovery",
            name="edges",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True, default="", editable=False, null=True
                    ),
                    default=list,
                    size=2,
                ),
                default=list,
                size=None,
                verbose_name="Edges",
            ),
        ),
        migrations.AlterField(
            model_name="discovery",
            name="nodes",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                null=True,
                verbose_name="Nodes",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="edges",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(
                        blank=True, default="", editable=False, null=True
                    ),
                    default=list,
                    size=2,
                ),
                default=list,
                size=None,
                verbose_name="Edges",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="nodes",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                null=True,
                verbose_name="Nodes",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="tcp_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, default=0),
                default=discovery.domain.popular_ports.popular_tcp_ports,
                size=None,
                verbose_name="TCP Ports",
            ),
        ),
        migrations.AlterField(
            model_name="scanner",
            name="udp_ports",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, default=0),
                default=discovery.domain.popular_ports.popular_udp_ports,
                size=None,
                verbose_name="UDP Ports",
            ),
        ),
    ]
